### PR TITLE
Fingerprint NaveenRayappan

### PR DESCRIPTION
**Pull request by NaveenRayappan**
Fingerprint NaveenRayappan features by NAVEENRAYAPPAN

### CODE REVIEW

**Comment by NaveenRayappan** [comment]
FINGERPRINT BY NAVEENRAYAPPAN

**Review by NaveenRayappan — COMMENTED** [review]
OK

**Comment by NaveenRayappan** [comment]
OK DONE

**Comment by NaveenRayappan1808** [comment]
finally updated easy fingerprints.

**Pull request merged**
